### ISSUE TITLE
instrucrtions page.

### ISSUE THREAD

**Issue by vikashupadhyay** [nabeel95/BattleShip#2]
if i know username of opponent player i can disturb the game . so go to instruction page and write some instruction for player that player don't tell his name to  opponent player.

**Comment by sagarising** [comment]
We already thought about the issue that is why we don't disclose the opponents name until the game is over. But we will try to make it more secure in further release.

**Comment by sagarising** [comment]
As you said we have updated our instruction page. Have a look at battleship-step2015.rhcloud.com
